# Generated by Django 4.0.3 on 2022-04-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_alter_sight_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
