# Generated by Django 4.0.3 on 2022-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0003_alter_sight_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sight',
            name='image_preview',
        ),
        migrations.AddField(
            model_name='sight',
            name='image',
            field=models.ImageField(default='test', upload_to='images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
