# Generated by Django 4.0.3 on 2022-04-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_popularpeople_bored_alter_popularpeople_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularpeople',
            name='died',
            field=models.DateField(blank=True, default='2022-04-02', verbose_name='Дата смерти'),
            preserve_default=False,
        ),
    ]
