# Generated by Django 4.0.3 on 2022-04-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_popularpeople_died'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularpeople',
            name='died',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
    ]
