# Generated by Django 4.0.3 on 2022-04-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_popularpeople_died'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestingfact',
            name='image',
        ),
    ]
